run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.22'

directories:
  exclude:
    - vendor/

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

# Output configuration
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0
  # Use colored output
  include-use-line-number: true
